[project]
name = "repl-nix-enlightenintled"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "nltk>=3.9.1",
    "openai>=1.54.3",
    "plotly>=5.24.1",
    "pypdf2>=3.0.1",
    "streamlit>=1.40.1",
]
